make readme more readable
backstage/actions pull request #39
Opened 2022-07-04 13:09 UTC by jhaals

2022-07-04 13:10 UTC, Rugvip requested changes
UNACCEPTABLE

2022-07-04 13:10 UTC, jhaals commented
NO!

2022-07-04 13:11 UTC, Rugvip requested changes
UNACCEPTABLE

2022-07-04 13:11 UTC, Rugvip commented on README.md
> +
BUT SPACE

2022-07-04 13:12 UTC, jhaals commented on README.md
> +
WE NEED IT!

2022-07-04 13:13 UTC, benjdlambert commented on README.md
> +
NO SPACE

2022-07-05 14:20 UTC, Rugvip commented on README.md
> +
SPACE

2022-07-05 14:24 UTC, Rugvip commented
SPACE

2022-07-05 14:36 UTC, Rugvip commented on README.md
> +
MORE SPACE

2022-07-05 15:52 UTC, Rugvip commented on README.md
> +
INFINITE SPACE

2022-07-05 16:00 UTC, Rugvip commented on README.md
> +
INFINITE INFINITE SPACE

2022-07-05 16:11 UTC, Rugvip commented on README.md
> +
SO MUCH SPACE

2022-07-05 16:20 UTC, Rugvip commented on README.md
> +
👾

2022-07-05 16:22 UTC, Rugvip commented on README.md
> +
🛰️

2022-07-06 12:08 UTC, closed without merging